import { Provider } from "@project-serum/anchor";

import { clusterApiUrl, Connection } from "@solana/web3.js";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import idl from "../idl.json";

const Home: NextPage = () => {
  console.log(idl);

  useEffect(() => {
    const connection = new Connection(clusterApiUrl("devnet"), "confirmed");
    const provider = new Provider(
      connection,
      // @ts-ignore
      window.solana,
      {}
    );
    console.log(provider);
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ padding: 20 }}>
        <h1>Solana App!</h1>
      </div>
    </div>
  );
};

export default Home;
